config/routes.rb
Spree::Core::Engine.add_routes do
  namespace :admin do
    get '/search/users', to: "search#users", as: :search_users
    get '/search/products', to: "search#products", as: :search_products

    resources :promotions do
      resources :promotion_rules
      resources :promotion_actions
    end

    resources :promotion_categories, except: [:show]

    resources :zones

    resources :countries do
      resources :states
    end
    resources :states
    resources :tax_categories

    resources :products do
      resources :product_properties do
        collection do
          post :update_positions
        end
      end
      resources :images do
        collection do
          post :update_positions
        end
      end
      member do
        get :clone
        get :stock
      end
      resources :variants do
        collection do
          post :update_positions
        end
      end
      resources :variants_including_master, only: [:update]
    end

    get '/variants/search', to: "variants#search", as: :search_variants

    resources :option_types do
      collection do
        post :update_positions
        post :update_values_positions
      end
    end

    delete '/option_values/:id', to: "option_values#destroy", as: :option_value

    resources :properties do
      collection do
        get :filtered
      end
    end

    delete '/product_properties/:id', to: "product_properties#destroy", as: :product_property

    resources :prototypes do
      member do
        get :select
      end

      collection do
        get :available
      end
    end

    resources :orders, except: [:show] do
      member do
        get :cart
        post :resend
        get :open_adjustments
        get :close_adjustments
        put :approve
        put :cancel
        put :resume
      end

      resources :state_changes, only: [:index]

      resource :customer, controller: "orders/customer_details"
      resources :customer_returns, only: [:index, :new, :edit, :create, :update] do
        member do
          put :refund
        end
      end

      resources :adjustments
      resources :return_authorizations do
        member do
          put :fire
        end
      end
      resources :payments do
        member do
          put :fire
        end

        resources :log_entries
        resources :refunds, only: [:new, :create, :edit, :update]
      end

      resources :reimbursements, only: [:index, :create, :show, :edit, :update] do
        member do
          post :perform
        end
      end
    end

    resource :general_settings do
      collection do
        post :dismiss_alert
        post :clear_cache
      end
    end

    resources :return_items, only: [:update]

    resources :taxonomies do
      collection do
        post :update_positions
      end
      resources :taxons
    end

    resources :taxons, only: [:index, :show] do
      collection do
        get :search
      end
    end

    resources :reports, only: [:index] do
      collection do
        get :sales_total
        post :sales_total
      end
    end

    resources :reimbursement_types, only: [:index]
    resources :refund_reasons, except: [:show, :destroy]
    resources :return_authorization_reasons, except: [:show, :destroy]

    resources :shipping_methods
    resources :shipping_categories
    resources :stock_transfers, only: [:index, :show, :new, :create]
    resources :stock_locations do
      resources :stock_movements, except: [:edit, :update, :destroy]
      collection do
        post :transfer_stock
      end
    end

    resources :stock_items, only: [:create, :update, :destroy]
    resources :tax_rates

    resources :trackers
    resources :payment_methods
    resources :roles

    resources :users do
      member do
        get :orders
        get :items
        get :addresses
        put :addresses
      end
    end
  end

  get '/admin', to: 'admin/root#index', as: :admin
end

app/controllers/spree/admin/taxonomies_controller.rb
module Spree
  module Admin
    class TaxonomiesController < ResourceController
      private

      def location_after_save
        if @taxonomy.created_at == @taxonomy.updated_at
          edit_admin_taxonomy_url(@taxonomy)
        else
          admin_taxonomies_url
        end
      end
    end
  end
end

app/views/spree/admin/taxonomies/_form.html.erb
<div data-hook="admin_inside_taxonomy_form" class="form-group">
  <%= f.field_container :name, class: ['form-group'] do %>
    <%= f.label :name, Spree.t(:name) %> <span class="required">*</span>
    <%= error_message_on :taxonomy, :name, :class => 'error-message' %>
    <%= text_field :taxonomy, :name, :class => 'form-control' %>
  <% end %>
</div>

app/views/spree/admin/taxonomies/_js_head.html.erb
<% content_for :head do %>
  <%= javascript_tag "var taxonomy_id = #{@taxonomy.id};
    var loading = '#{escape_javascript Spree.t(:loading)}';
    var new_taxon = '#{escape_javascript Spree.t(:new_taxon)}';
    var server_error = '#{escape_javascript Spree.t(:server_error)}';
    var taxonomy_tree_error = '#{escape_javascript Spree.t(:taxonomy_tree_error)}';

    $(document).ready(function(){
      setup_taxonomy_tree(taxonomy_id);
    });
    "
  %>
<% end %>

app/views/spree/admin/taxonomies/_list.html.erb
<table class="table sortable" id='listing_taxonomies' data-hook data-sortable-link="<%= update_positions_admin_taxonomies_url %>">
  <thead>
    <tr data-hook="taxonomies_header">
      <th class="no-border"></th>
      <th><%= Spree.t(:name) %></th>
      <th class="actions"></th>
    </tr>
  </thead>
  <tbody>
    <% @taxonomies.each do |taxonomy| %>
      <tr id="<%= spree_dom_id taxonomy %>" data-hook="taxonomies_row">
        <td class="move-handle">
          <span class="icon icon-sort handle"></span>
        </td>
        <td><%= taxonomy.name %></td>
        <td class="actions actions-2 text-right">
          <%= link_to_edit taxonomy.id, no_text: true %>
          <%= link_to_delete taxonomy, no_text: true %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/spree/admin/taxonomies/edit.erb
<%= render partial: 'js_head' %>

<% content_for :page_title do %>
  <%= Spree.t(:taxonomy_edit) %>
<% end %>

<div id="ajax_error" class="errorExplanation" style="display:none;"></div>

<%= form_for [:admin, @taxonomy] do |f| %>
  <fieldset>
    <%= render partial: 'form', locals: { f: f } %>
    <div class="form-group">
      <%= label_tag nil, Spree.t(:tree) %>
      <script>
        Spree.routes.taxonomy_taxons_path = "<%= spree.api_taxonomy_taxons_path(@taxonomy) %>";
        Spree.routes.admin_taxonomy_taxons_path = "<%= spree.admin_taxonomy_taxons_path(@taxonomy) %>";
        Spree.routes.jstree_theme_path = "<%= stylesheet_path("jquery.jstree/themes/spree/style.css") %>";
      </script>
      <div id="taxonomy_tree" class="tree">
        <div class="alert alert-warning">
          <%= Spree.t(:loading_tree) %>
        </div>
      </div>
    </div>

    <div class="alert alert-info">
      <%= Spree.t(:taxonomy_tree_instruction) %>
    </div>

    <div class="form-actions">
      <%= button Spree.t('actions.update'), 'ok', 'submit', { class: 'btn-success' } %>
      <span class="or"><%= Spree.t(:or) %></span>
      <%= button_link_to Spree.t('actions.cancel'), admin_taxonomies_path, icon: 'delete' %>
    </div>
  </fieldset>
<% end %>

app/views/spree/admin/taxonomies/index.html.erb
<% content_for :page_title do %>
  <%= plural_resource_name(Spree::Taxonomy) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:new_taxonomy), new_object_url, class: "btn-success", icon: 'add', id: 'admin_new_taxonomy_link' %>
<% end %>

<% if @taxonomies.any? %>
  <div id="list-taxonomies" data-hook>
    <%= render 'list' %>
  </div>
<% else %>
  <div class="alert alert-info no-objects-found">
    <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::Taxonomy)) %>,
    <%= link_to Spree.t(:add_one), new_object_url %>!
  </div>
<% end %>

app/views/spree/admin/taxonomies/new.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:new_taxonomy) %>
<% end %>

<%= form_for [:admin, @taxonomy] do |f| %>
  <fieldset>
    <%= render :partial => 'form', :locals => { :f => f } %>
    <div class="form-actions" data-hook="buttons">
      <%= button Spree.t(:create), 'save' %>
    </div>
  </fieldset>
<% end %>