config/routes.rb
Spree::Core::Engine.add_routes do
  namespace :admin do
    get '/search/users', to: "search#users", as: :search_users
    get '/search/products', to: "search#products", as: :search_products

    resources :promotions do
      resources :promotion_rules
      resources :promotion_actions
    end

    resources :promotion_categories, except: [:show]

    resources :zones

    resources :countries do
      resources :states
    end
    resources :states
    resources :tax_categories

    resources :products do
      resources :product_properties do
        collection do
          post :update_positions
        end
      end
      resources :images do
        collection do
          post :update_positions
        end
      end
      member do
        get :clone
        get :stock
      end
      resources :variants do
        collection do
          post :update_positions
        end
      end
      resources :variants_including_master, only: [:update]
    end

    get '/variants/search', to: "variants#search", as: :search_variants

    resources :option_types do
      collection do
        post :update_positions
        post :update_values_positions
      end
    end

    delete '/option_values/:id', to: "option_values#destroy", as: :option_value

    resources :properties do
      collection do
        get :filtered
      end
    end

    delete '/product_properties/:id', to: "product_properties#destroy", as: :product_property

    resources :prototypes do
      member do
        get :select
      end

      collection do
        get :available
      end
    end

    resources :orders, except: [:show] do
      member do
        get :cart
        post :resend
        get :open_adjustments
        get :close_adjustments
        put :approve
        put :cancel
        put :resume
      end

      resources :state_changes, only: [:index]

      resource :customer, controller: "orders/customer_details"
      resources :customer_returns, only: [:index, :new, :edit, :create, :update] do
        member do
          put :refund
        end
      end

      resources :adjustments
      resources :return_authorizations do
        member do
          put :fire
        end
      end
      resources :payments do
        member do
          put :fire
        end

        resources :log_entries
        resources :refunds, only: [:new, :create, :edit, :update]
      end

      resources :reimbursements, only: [:index, :create, :show, :edit, :update] do
        member do
          post :perform
        end
      end
    end

    resource :general_settings do
      collection do
        post :dismiss_alert
        post :clear_cache
      end
    end

    resources :return_items, only: [:update]

    resources :taxonomies do
      collection do
        post :update_positions
      end
      resources :taxons
    end

    resources :taxons, only: [:index, :show] do
      collection do
        get :search
      end
    end

    resources :reports, only: [:index] do
      collection do
        get :sales_total
        post :sales_total
      end
    end

    resources :reimbursement_types, only: [:index]
    resources :refund_reasons, except: [:show, :destroy]
    resources :return_authorization_reasons, except: [:show, :destroy]

    resources :shipping_methods
    resources :shipping_categories
    resources :stock_transfers, only: [:index, :show, :new, :create]
    resources :stock_locations do
      resources :stock_movements, except: [:edit, :update, :destroy]
      collection do
        post :transfer_stock
      end
    end

    resources :stock_items, only: [:create, :update, :destroy]
    resources :tax_rates

    resources :trackers
    resources :payment_methods
    resources :roles

    resources :users do
      member do
        get :orders
        get :items
        get :addresses
        put :addresses
      end
    end
  end

  get '/admin', to: 'admin/root#index', as: :admin
end

app/controllers/spree/admin/general_settings_controller.rb
module Spree
  module Admin
    class GeneralSettingsController < Spree::Admin::BaseController
      include Spree::Backend::Callbacks

      before_action :set_store

      def edit
        @preferences_security = [:check_for_spree_alerts]
      end

      def update
        params.each do |name, value|
          next unless Spree::Config.has_preference? name
          Spree::Config[name] = value
        end

        current_store.update_attributes store_params

        flash[:success] = Spree.t(:successfully_updated, resource: Spree.t(:general_settings))
        redirect_to edit_admin_general_settings_path
      end

      def dismiss_alert
        if request.xhr? and params[:alert_id]
          dismissed = Spree::Config[:dismissed_spree_alerts] || ''
          Spree::Config.set dismissed_spree_alerts: dismissed.split(',').push(params[:alert_id]).join(',')
          filter_dismissed_alerts
          render nothing: true
        end
      end

      def clear_cache
        Rails.cache.clear
        invoke_callbacks(:clear_cache, :after)
        head :no_content
      end

      private
      def store_params
        params.require(:store).permit(permitted_store_attributes)
      end

      def set_store
        @store = current_store
      end
    end
  end
end

app/helpers/spree/admin/general_settings_helper.rb
module Spree
  module Admin
    module GeneralSettingsHelper
      def currency_options
        currencies = ::Money::Currency.table.map do |code, details|
          iso = details[:iso_code]
          [iso, "#{details[:name]} (#{iso})"]
        end
        options_from_collection_for_select(currencies, :first, :last, Spree::Config[:currency])
      end
    end
  end
end

app/views/spree/admin/general_settings/edit.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:general_settings) %>
<% end %>

<%= form_tag admin_general_settings_path, method: :put do %>
  <div id="preferences" data-hook>

    <fieldset class="general no-border-top">

      <%= fields_for :store do |f| %>
        <div class="row">
          <div class="col-md-6">
            <div class="form-group" data-hook="admin_general_setting_input_name">
              <%= f.label :name %>
              <%= f.text_field :name, class: 'form-control' %>
            </div>
          </div>

          <div class="col-md-6">
            <div class="form-group" data-hook="admin_general_setting_input_seo_title">
              <%= f.label :seo_title %>
              <%= f.text_field :seo_title, class: 'form-control'  %>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-md-6">
            <div class="form-group" data-hook="admin_general_setting_input_meta_keywords">
              <%= f.label :meta_keywords %>
              <%= f.text_field :meta_keywords, class: 'form-control'  %>
            </div>
          </div>

          <div class="col-md-6">
            <div class="form-group" data-hook="admin_general_setting_input_meta_description">
              <%= f.label :meta_description %>
              <%= f.text_field :meta_description, class: 'form-control'  %>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-md-6">
            <div class="form-group" data-hook="admin_general_setting_input_url">
              <%= f.label :url %>
              <%= f.text_field :url, class: 'form-control'  %>
            </div>
          </div>

          <div class="col-md-6">
            <div class="form-group" data-hook="admin_general_setting_mail_from_address">
              <%= f.label :mail_from_address %>
              <%= f.text_field :mail_from_address, class: 'form-control'  %>
            </div>
          </div>
        </div>
      <% end %>

      <div class="row">
        <div class="col-md-6">

          <%#-------------------------------------------------%>
          <%# Security settings                               %>
          <%#-------------------------------------------------%>
          <div class="panel panel-default security">
            <div class="panel-heading">
              <h1 class="panel-title">
                <%= Spree.t(:security_settings)%>
              </h1>
            </div>

            <div class="panel-body">
              <% @preferences_security.each do |key|
                  type = Spree::Config.preference_type(key) %>
                  <div class="checkbox">
                    <%= label_tag key do %>
                      <%= preference_field_tag(key, Spree::Config[key], type: type) %>
                      <%= Spree.t(key) %>
                    <% end %>
                  </div>
              <% end %>
            </div>
          </div>

          <%#-------------------------------------------------%>
          <%# Clear cache                                     %>
          <%#-------------------------------------------------%>
          <div class="panel panel-default">
            <div class="panel-heading">
              <h1 class="panel-title"><%= Spree.t(:clear_cache)%></h1>
            </div>

            <div class="panel-body">
              <div class="clear-cache-warning alert alert-warning">
                <%= Spree.t(:clear_cache_warning) %>
              </div>
              <div data-hook="general_settings_clear_cache">
                <%= button Spree.t(:clear_cache), 'ok', 'button', id: "clear_cache" %>
              </div>
            </div>
          </div>

        </div>
        <div class="col-md-6">

          <%#-------------------------------------------------%>
          <%# Currency Settings                               %>
          <%#-------------------------------------------------%>
          <div class="panel panel-default currency">
            <div class="panel-heading">
              <h1 class="panel-title">
                <%= Spree.t(:currency_settings)%>
              </h1>
            </div>

            <div class="panel-body">
              <div class="form-group">
                <%= label_tag :currency, Spree.t(:choose_currency) %>
                <%= select_tag :currency, currency_options %>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="form-actions" data-hook="buttons">
        <%= button Spree.t('actions.update'), 'save' %>
        <span class="or"><%= Spree.t(:or) %></span>
        <%= button_link_to Spree.t('actions.cancel'), edit_admin_general_settings_url, icon: 'delete' %>
      </div>

    </fieldset>

  </div>

<% end %>

<script>
  $('#store_default_currency').select2();
  $('#currency').select2();
</script>